### ISSUE TITLE
erro ao executar a lib

### ISSUE THREAD

**Issue by silviostanzani** [Residencia-Fiep-Turma-2/projeto-biodiversidade#20]
(bio) Spraces-MacBook-Pro:git silvio$ git clone https://github.com/Residencia-Fiep-Turma-2/projeto-biodiversidade.git
Cloning into 'projeto-biodiversidade'...
remote: Enumerating objects: 202, done.
remote: Counting objects: 100% (202/202), done.
remote: Compressing objects: 100% (127/127), done.
remote: Total 202 (delta 62), reused 120 (delta 38), pack-reused 0
Receiving objects: 100% (202/202), 56.61 KiB | 394.00 KiB/s, done.
Resolving deltas: 100% (62/62), done.
(bio) Spraces-MacBook-Pro:git silvio$ cd projeto-biodiversidade/
(bio) Spraces-MacBook-Pro:projeto-biodiversidade silvio$ nano tt.py
(bio) Spraces-MacBook-Pro:projeto-biodiversidade silvio$ pip install -i https://test.pypi.org/simple/ pkg-biodiversidade
Looking in indexes: https://test.pypi.org/simple/
Requirement already satisfied: pkg-biodiversidade in /Users/silvio/miniconda2/envs/bio/lib/python3.8/site-packages (0.0.1)
(bio) Spraces-MacBook-Pro:projeto-biodiversidade silvio$ pip install opencage
Requirement already satisfied: opencage in /Users/silvio/miniconda2/envs/bio/lib/python3.8/site-packages (1.2.1)
Requirement already satisfied: Requests>=2.2.0 in /Users/silvio/.local/lib/python3.8/site-packages (from opencage) (2.23.0)
Requirement already satisfied: pyopenssl>=0.15.1 in /Users/silvio/miniconda2/envs/bio/lib/python3.8/site-packages (from opencage) (19.1.0)
Requirement already satisfied: six>=1.4.0 in /Users/silvio/miniconda2/envs/bio/lib/python3.8/site-packages (from opencage) (1.15.0)
Requirement already satisfied: backoff>=1.10.0 in /Users/silvio/miniconda2/envs/bio/lib/python3.8/site-packages (from opencage) (1.10.0)
Requirement already satisfied: certifi>=2017.4.17 in /Users/silvio/miniconda2/envs/bio/lib/python3.8/site-packages (from Requests>=2.2.0->opencage) (2020.6.20)
Requirement already satisfied: idna<3,>=2.5 in /Users/silvio/.local/lib/python3.8/site-packages (from Requests>=2.2.0->opencage) (2.9)
Requirement already satisfied: chardet<4,>=3.0.2 in /Users/silvio/.local/lib/python3.8/site-packages (from Requests>=2.2.0->opencage) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /Users/silvio/.local/lib/python3.8/site-packages (from Requests>=2.2.0->opencage) (1.25.9)
Requirement already satisfied: cryptography>=2.8 in /Users/silvio/miniconda2/envs/bio/lib/python3.8/site-packages (from pyopenssl>=0.15.1->opencage) (3.1)
Requirement already satisfied: cffi!=1.11.3,>=1.8 in /Users/silvio/miniconda2/envs/bio/lib/python3.8/site-packages (from cryptography>=2.8->pyopenssl>=0.15.1->opencage) (1.14.2)
Requirement already satisfied: pycparser in /Users/silvio/miniconda2/envs/bio/lib/python3.8/site-packages (from cffi!=1.11.3,>=1.8->cryptography>=2.8->pyopenssl>=0.15.1->opencage) (2.20)
(bio) Spraces-MacBook-Pro:projeto-biodiversidade silvio$ cat tt.py
from pkg_biodiversidade import Bio
bio1 = Bio.Bio("/Users/silvio/git/biodiversidade-ggr/data/portalbio_canidae.csv")
bio1.media()
(bio) Spraces-MacBook-Pro:projeto-biodiversidade silvio$ python tt.py
Traceback (most recent call last):
  File "tt.py", line 1, in <module>
    from pkg_biodiversidade import Bio
ModuleNotFoundError: No module named 'pkg_biodiversidade'

**Comment by TgoPedrosa** [comment]
Olá Silvio, esse problema foi resolvido com um novo release do pacote. O novo link já está disponível na [Wiki](https://github.com/Residencia-Fiep-Turma-2/projeto-biodiversidade/wiki/Como-instalar#onde-conseguir)
