### ISSUE TITLE
Problema nos filtros por linhas e colunas sem o pandas

### ISSUE THREAD

**Issue by PedroNunes92** [Residencia-Fiep-Turma-2/projeto-biodiversidade#24]
Seguindo o wiki do projeto, tentei utilizar o filtro das colunas "Responsável pelo registro" e "Data do evento", porém ele está retornando "None". Já tentei em dois arquivos de dados e acontece a mesma coisa.

**Comment by nagahamaVH** [comment]
@PedroNunes92 você consegue colocar aqui o código que você está executando?

**Comment by PedroNunes92** [comment]
from pkg_biodiversidade import Bio

bio1 = Bio.Bio("/home/pedronunes/Downloads/portalbio_export_08-09-2020-13-05-29/portalbio_export_08-09-2020-13-05-29.csv")
#/home/pedronunes/Downloads/portalbio_export_31-08-2020-14-39-10.csv
#bio1.media()
#print("Funcionalidade de média de dados faltantes por coluna\n")
#print(bio1.media())

#bio1.checaNivelTaxonomico() 
#print(bio1.checaNivelTaxonomico())
#result = bio1.checaNivelTaxonomico()
#for i in range(1,len(result) - 1):
#    print("Nível taxônomico registro " + str(i) + " - " + result[i])


**#filtrandos os valores das colunas "Responsavel pelo registro" e "Data do evento"
colunas = ["Responsavel pelo registro", "Data do evento"]
print(bio1.select_columns(colunas))
#filtrando a linha de acordo com a coluna "Numero do registro no portal" com o valor de "1043087"
coluna = "Numero do registro no portal"
valor = "1043087"
print(bio1.filter_rows(coluna, valor))
## N RETORNA NONE**


#Funcionalidade 4
#print("\n")
#print("Funcionalidade para checar a longitude e latitude corresponde com a localização\n")
#bio1.verifica_lat_long()

**Comment by PedroNunes92** [comment]
from pkg_biodiversidade import Bio

bio1 = Bio.Bio("/home/pedronunes/Downloads/portalbio_export_08-09-2020-13-05-29/portalbio_export_08-09-2020-13-05-29.csv")
#/home/pedronunes/Downloads/portalbio_export_31-08-2020-14-39-10.csv
#bio1.media()
#print("Funcionalidade de média de dados faltantes por coluna\n")
#print(bio1.media())

#bio1.checaNivelTaxonomico() 
#print(bio1.checaNivelTaxonomico())
#result = bio1.checaNivelTaxonomico()
#for i in range(1,len(result) - 1):
#print("Nível taxônomico registro " + str(i) + " - " + result[i])

#funcionalidade 3
#filtrandos os valores das colunas "Responsavel pelo registro" e "Data do evento"
colunas = ["Responsavel pelo registro", "Data do evento"]
print(bio1.select_columns(colunas))
#filtrando a linha de acordo com a coluna "Numero do registro no portal" com o valor de "1043087"
coluna = "Numero do registro no portal"
valor = "1043087"
print(bio1.filter_rows(coluna, valor))
##RETORNA NONE


#Funcionalidade 4
#print("\n")
#print("Funcionalidade para checar a longitude e latitude corresponde com a localização\n")
#bio1.verifica_lat_long()

**Comment by nagahamaVH** [comment]
> from pkg_biodiversidade import Bio
> 
> bio1 = Bio.Bio("/home/pedronunes/Downloads/portalbio_export_08-09-2020-13-05-29/portalbio_export_08-09-2020-13-05-29.csv")
> #/home/pedronunes/Downloads/portalbio_export_31-08-2020-14-39-10.csv
> #bio1.media()
> #print("Funcionalidade de média de dados faltantes por coluna\n")
> #print(bio1.media())
> 
> #bio1.checaNivelTaxonomico()
> #print(bio1.checaNivelTaxonomico())
> #result = bio1.checaNivelTaxonomico()
> #for i in range(1,len(result) - 1):
> #print("Nível taxônomico registro " + str(i) + " - " + result[i])
> 
> #funcionalidade 3
> #filtrandos os valores das colunas "Responsavel pelo registro" e "Data do evento"
> colunas = ["Responsavel pelo registro", "Data do evento"]
> print(bio1.select_columns(colunas))
> #filtrando a linha de acordo com a coluna "Numero do registro no portal" com o valor de "1043087"
> coluna = "Numero do registro no portal"
> valor = "1043087"
> print(bio1.filter_rows(coluna, valor))
> ##RETORNA NONE
> 
> #Funcionalidade 4
> #print("\n")
> #print("Funcionalidade para checar a longitude e latitude corresponde com a localização\n")
> #bio1.verifica_lat_long()

Quando você aplica um filtro ele não retorna em um novo objeto por isso o print retorna `None`. Ao aplicar o filtro o atributo `filtered_data` do objeto instanciado (`bio1`) é modificado, dessa forma você pode aplicar sucessivos filtros no conjunto de dados original.

Após aplicar um filtro você pode visualizar o conjunto filtrado pelo comando `print(bio1.filtered_data)`.

Lembrando que cada operação de filtro altera o atributo `filtered_data`, assim, o comando
`bio1.select_columns(colunas)
bio1.filter_rows("Numero do registro no portal", "1043087")
print(bio1.filtered_data)`
selecionará as colunas e a partir deste resultado irá selecionar as linhas tal que `Numero do registro no portal == "1043087"`

**Comment by PedroNunes92** [comment]
ahh entendi. Obrigado.

**Comment by nagahamaVH** [comment]
Caso não haja problemas fecharei a issue
