### ISSUE TITLE
Não consegui utilizar a Funcionalidade para exportar para .csv

### ISSUE THREAD

**Issue by nataliaasaa** [Residencia-Fiep-Turma-2/projeto-biodiversidade#25]
AttributeError: 'Bio' object has no attribute 'export_csv'

meu código: 
from pkg_biodiversidade import Bio

bio1 = Bio.Bio("/home/nataliasa/Downloads/onca.csv")

coluna = "Numero do registro no portal"
valor = "128381"
bio1.filter_rows(coluna, valor)
print (bio1.filtered_data)
bio1.export_csv("/home/nataliasa/Downloads/testegrupo4.csv")

**Comment by TgoPedrosa** [comment]
> AttributeError: 'Bio' object has no attribute 'export_csv'
> 
> meu código:
> from pkg_biodiversidade import Bio
> 
> bio1 = Bio.Bio("/home/nataliasa/Downloads/onca.csv")
> 
> coluna = "Numero do registro no portal"
> valor = "128381"
> bio1.filter_rows(coluna, valor)
> print (bio1.filtered_data)
> bio1.export_csv("/home/nataliasa/Downloads/testegrupo4.csv")

@nataliaasaa O erro está acontecendo porque a função export_csv não existe, o correto é write_csv. A wiki estava com o nome da função errada, mas agora já está atualizada com nome correto. 
https://github.com/Residencia-Fiep-Turma-2/projeto-biodiversidade/wiki/Como-utilizar#funcionalidade-para-exportar-para-csv

**Comment by nataliaasaa** [comment]
Preciso colocar alguma coisa no meu código além de trocar o nome? ainda não funcionou.
TypeError: sequence item 0: expected str instance, list found

**Comment by TgoPedrosa** [comment]
> Preciso colocar alguma coisa no meu código além de trocar o nome? ainda não funcionou.
> TypeError: sequence item 0: expected str instance, list found

Realmente estava com erro nessa parte de exportar após filtrar por linha. O erro já foi corrigido na nova versão do pacote.
O recomendado é desinstalar o pacote e instalar de novo

```
pip uninstall pkg-biodiversidade
pip install -i https://test.pypi.org/simple/ pkg-biodiversidade
```
ou instalar por cima a nova versão

```
pip install -i https://test.pypi.org/simple/ pkg-biodiversidade==3.3.0
```
Caso o csv exportado esteja vazio, é por conta do valor do filtro, tem que usar uma coluna e um valor que tenha no CSV que está sendo usado

**Comment by nataliaasaa** [comment]
Agora deu certo. Obrigada!
