### ISSUE TITLE
Documentação da solução

### ISSUE THREAD

**Issue by nagahamaVH** [Residencia-Fiep-Turma-2/projeto-biodiversidade#7]
Formato Livre
Sugiro que utilizem a wiki do repositório git, pois aceita markdown
A idéia é que os outros grupos possam utilizar as suas classes para testes, para isso é importante a documentação, bem como, comentários no código.

**Comment by TgoPedrosa** [comment]
Closed in https://github.com/Residencia-Fiep-Turma-2/projeto-biodiversidade/wiki
