### ISSUE TITLE
Teste de uma das classes implementadas por outros grupos

### ISSUE THREAD

**Issue by nagahamaVH** [Residencia-Fiep-Turma-2/projeto-biodiversidade#9]
Teste de uma das classes implementadas por outros grupos com arquivos de entrada obtidos por voce no portal, e um texto dos erros obtidos usando uma classe de outro grupo (resultados e possivelmente erros)

**Comment by sergiohff** [comment]
biodiversidade-ggr: 
quando for executar o comando: dataEvaluation = qualityEvaluation.qualityEvaluation("data/portalbio_example_1.csv") (conforme descrito no passo a passo)
tem o erro "AttributeError: module 'qualityEvaluation' has no attribute 'qualityEvaluation'"
executa com __init__("path")

outros grupos estão pendentes

**Comment by silviostanzani** [comment]
> biodiversidade-ggr:
> quando for executar o comando: dataEvaluation = qualityEvaluation.qualityEvaluation("data/portalbio_example_1.csv") (conforme descrito no passo a passo)
> tem o erro "AttributeError: module 'qualityEvaluation' has no attribute 'qualityEvaluation'"
> executa com **init**("path")
> 
> outros grupos estão pendentes

Sergio, vc deve incluir essa issue no repositório dos outros grupos

**Comment by sergiohff** [comment]
Foi criado issues referente aos erros e funcionalidades faltantes ao grupo biodiversidade-ggr
issue1 : https://github.com/Residencia-Fiep-Turma-2/biodiversidade-ggr/issues/11
issue2 : https://github.com/Residencia-Fiep-Turma-2/biodiversidade-ggr/issues/12
